name: crypto_radar
description: Crypto Radar Application
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
